### ISSUE TITLE
Playing in a self hosted server with a single friend clones their character repeatedly

### ISSUE THREAD

**Issue by Tondrin** [MidnightsFX/Valheim_Armory#24] opened 2024-06-05 01:29 UTC
After the update on june 2nd, valheim armory has started to cause an issue when enabled that has my friends character just start multiplying until frames grind in a halt. We've tested the other mods and it's armory that seems to be causing the issue. I as the host don't run into the issue and me and my friend have verified we're using the same mod list.

**Comment by MidnightsFX** [comment] 2024-06-05 01:34
This is caused by a schism in the configurations between the client and the server, specifically recipes and disabled items.

Both of you should use the same config. I generally suggest just deleting your config and using the generated default for both of you.

I'm looking into having this issue automatically handled, but for now the fix is just a config delete.

**Comment by MidnightsFX** [comment] 2024-06-05 18:28
Hey @Tondrin This should be fixed in 1.10.0

I'll leave this open for a little while if you have time to verify, and then close it.

**Closed** 2024-06-07 04:08 UTC
Labels: bug
