### ISSUE TITLE
warning in log

### ISSUE THREAD

**Issue by PaloAlo** [MidnightsFX/Valheim_Armory#8] opened 2023-05-22 16:39 UTC
[Warning:ValheimArmory.ValArmoryItem] Configuration 'Arrows - Wood Bolt - WoodBolt-recipe' was invalid and will be ignored, the default will be used.

i tried fiddling with the recipe in the config, but i think its something set incorrectly in unity when you made it.

**Comment by MidnightsFX** [comment] 2023-05-23 03:59
@PaloAlo could you provide the recipe config for the Wood Bolt as you have it?

**Comment by PaloAlo** [comment] 2023-05-23 17:08
its literally on a default install. these are the logs off my test server and test profile from R2. the client log shows the arrow warning, and the server log shows something about mock textures, since your build is jotunn based i know its from your mod as well

[client LogOutput.log](https://github.com/MidnightsFX/Valheim_Armory/files/11546750/client.LogOutput.log)
[server LogOutput.log](https://github.com/MidnightsFX/Valheim_Armory/files/11546751/server.LogOutput.log)

**Comment by PaloAlo** [comment] 2023-05-24 15:54
i know in wackydb theres an option to "requireOnlyOneIngredient: false" which is i assume is also a Unity option.

like you say its probably looking for more than one unless this option is set to True.

for what its worth i tried making a recipe file and setting this option in wackydb but i still got the warning because it loads in earlier than wackysdb does. so.. Unity thing.

what about the mock textures? fixed that too?
![image](https://github.com/MidnightsFX/Valheim_Armory/assets/107334373/e6d3ae4c-5e8f-41a3-9852-1231a72206ea)

**Comment by MidnightsFX** [comment] 2023-05-24 16:49
Interesting! I don't have any warnings about that- are you running the beta Valheim branch?

**Comment by PaloAlo** [comment] 2023-05-24 16:59
Latest jotunn and current game version. Not beta.

**Comment by MidnightsFX** [comment] 2023-05-24 19:49
Yeah that particular particle I am mocking through jotunn to get the real in-game one.

The mock that I setup is an actual replacement though, but its not a perfect match to vanilla hence why I wanted to mock it.

I'll see about removing it as a mock. I am very curious why you are getting that issue and I can't reproduce it though.

**Comment by MidnightsFX** [comment] 2023-05-25 03:22
I do generally only test in singleplayer, but that particular mock has existed for a very long time and I have tested with a dedicated server since setting it up and didn't see any issues.

Are you maybe playing on a steam deck or on linux?

**Comment by PaloAlo** [comment] 2023-05-25 03:27
Playing on windows 10/11

Set up a dedi server on same machine as client thru steam as a test server.

Also set up a dedi server on a separate box in the house which runs a
public world.

Everything is windows. Everything is up to date.

I do have a gportal linux server but havent tested it there since that is
my main.

**Comment by MidnightsFX** [comment] 2023-05-25 03:32
Interesting! Do you use the steam or windows games version of valheim?

Either way I'll get this fixed in the next update by just not mocking that
particular thing.

**Comment by PaloAlo** [comment] 2023-05-25 03:44
I purchased valheim thru steam. Ive never had the opportunity to try any
other platforms.

**Comment by MidnightsFX** [comment] 2023-05-25 03:48
Welp, I guess I'll just have to keep an eye on other mocks in the future! Thanks!

This will be fixed in the next update, which should be pretty small and I'll likely get it out later today or tomorrow.

**Comment by PaloAlo** [comment] 2023-05-25 03:57
Thx for the update. Everything else seems to be working well.

**Closed** 2023-05-25 05:06 UTC
Labels: bug, fixed
